# Generated by Django 4.1.5 on 2023-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=80)),
                ('ip', models.CharField(max_length=30)),
                ('agent', models.TextField()),
            ],
        ),
    ]
